services:
  - type: web
    name: backend-ecommerce-cosmetics
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        value: mongodb+srv://jaiadhithyak_db_user:Jai_MongoDb%40123@cluster0.ulvqjzi.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        value: GlowBeauty_2024_SecureJWT_Key_9x8z7y6w5v4u3t2s1r0q_ProductionReady
      - key: ALLOWED_ORIGINS
        value: https://jaiadhithyak.netlify.app,http://localhost:5173